version: '3.9'

services:
  mariadb:
    container_name: db
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=rickandmorty
    networks:
      - doz
  doz:
    container_name: doz
    build: .
    ports:
      - "8080:8080"
    networks:
      - doz

networks:
  doz:
    driver: bridge
